### ISSUE TITLE
Inquiry about permission of usage of the repo for education and research purpose

### ISSUE THREAD

**Issue by zhongfendeng** [frandorado/spring-projects#15]
Hi Francisco,

Hope you are doing well! This is Zhongfen Deng, who is a PhD student at the University of Illinois Chicago. I am sending this message to inquire about the permission of using all the java projects in this repo for education and research purpose. If they can be used for the research purpose, I would really appreciate it. Looking forwarding to hearing from you.

Best Regards,
Zhongfen

**Comment by frandorado** [comment]
Hi @zhongfendeng,

No problem to use this repository for your educational and research purposes. I would appreciate if you indicate some reference to me in the references/credits of your research but of course this is optional.

Thanks.
